---
name: WebService-UWO-Directory-Service
version: 1.000001
author:
  - 'Jonathan Yu <frequency@cpan.org>'
abstract: |-
  Perform lookups using the University of Western Ontario's student directory
license: unrestricted
requires:
  Carp: 1.04
  HTML::Entities: 0
  LWP::UserAgent: 0
  Test::More: 0.62
  perl: 5.006
  strict: 0
  version: 0.76
  warnings: 0
build_requires:
  Test::NoWarnings: 0.084
recommends:
  Perl::Critic: 1.096
  Test::DistManifest: 1.001002
  Test::Kwalitee: 1.01
  Test::MinimumVersion: 0.008
  Test::Perl::Critic: 1.01
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
  Test::Portability::Files: 0.05
  Test::Signature: 1.1
  Test::Without::Module: 0.17
  Test::YAML::Meta: 0.11
dynamic_config: 0
provides:
  WebService::UWO::Directory::Student:
    file: lib/WebService/UWO/Directory/Student.pm
    version: 1.000001
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
resources:
  Ratings: http://cpanratings.perl.org/d/WebService-UWO-Directory-Student
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WebService-UWO-Directory-Student
  license: http://edwardsamuels.com/copyright/beyond/articles/public.html
  repository: http://svn.ali.as/cpan/trunk/WebService-UWO-Directory-Student
